VIAL_ENABLE = yes
LTO_ENABLE = yes

CUSTOM_MATRIX = yes
SRC += matrix.c

MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
AUDIO_ENABLE = no
ENCODER_ENABLE = no
OLED_ENABLE = no
