name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build-dacman:
    name: Build DacMan RP2040 Vial
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/qmk/qmk_cli@sha256:2dc05fc9f32efebd6b05c2b8676ee548358bc7e151e9dbf4dac6b6eed4513b07

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Diagnostics
        run: |
          git config --global --add safe.directory $(pwd)

          echo "========== CURRENT COMMIT =========="
          git rev-parse HEAD

          echo ""
          echo "========== WORKFLOW CONTENTS =========="
          cat .github/workflows/ci.yml

          echo ""
          echo "========== KEYMAP FILES =========="
          find keyboards/handwired/onekey/rp2040/keymaps -maxdepth 3 -type f -print

      - name: Compile DacMan firmware
        run: |
          git config --global --add safe.directory $(pwd)

          echo "========== BUILDING =========="

          make handwired/dacman:vial

          echo ""
          echo "========== UF2 FILES =========="
          find . -name "*.uf2" -print

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: Purple-Dac-Man-firmware
          path: |
            **/*.uf2
