name: CI

on: [pull_request, push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build-cantor:
    name: Build Cantor (Vial)
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli@sha256:2dc05fc9f32efebd6b05c2b8676ee548358bc7e151e9dbf4dac6b6eed4513b07

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Compile Cantor firmware
        run: |
          git config --global --add safe.directory $(pwd)

          echo "Building Cantor Vial firmware..."

          qmk compile -kb cantor -km vial

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: Purple-Dac-Man-firmware
          path: |
            *.uf2
